<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{config('app.name')}}</title>
    <link rel="stylesheet" href="{{base_path('public/css/bootstrap_trimmed.min.css')}}" />
    <style type="text/css">
        *{
            color: #000 !important;
        }
        html {
            height:100%;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin-left: 0.3in;
            margin-right: 0.3in;
        }
        h1 {
            font-size: 2em;
            font-weight: bold;
        }
        .vcenter {
            display: inline-block;
            vertical-align: middle;
            float: none;
        }
        .row {
            margin-bottom: 5px;
        }
        .page {
            page-break-after:always;
        }
        .overlay{
            position: relative;
        }
        .test{
            position: absolute;
            bottom: 1px; /* slight padding from bottom of image */
            left: 0;
            width: 100%;
            text-align: center;
        }
        .test p {
            line-height: 0.8;
        }
        .display{
            border-bottom: 1px solid black;
            text-align:center;
        }
        .no_margin{
            margin-left: 0 !important;
            margin-right: 0 !important;
            padding: 0 !important;
        }
       .title{
            font-size: 1rem;
            font-weight: 800;
            line-height: 0.8;
       }
        .display-text{
            height: 10px;
        }

        #print-date {
            position: fixed;
            bottom: 10px; /* adjust spacing from bottom */
            text-align: left;
            font-size: 12px;
            width: 100%;
            color: #555;
        }

    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="page">
            <div class="row" style="padding-top: 50px; padding-bottom: 25px">
                <div class="col-xs-7">
                    <div class="col-xs-7">
                        <p class="title"> Report Date</p>
                        <p class="title"> Date Issued</p>
                        <p class="title"> Generated By</p>
                    </div>

                    <div class="col-xs-5 test">
                        <p> {{$range}}</p>
                        <p> {{$created_at}}</p>
                        <p> {{$created_by}}</p>
                    </div>
                </div>
                <div class="col-xs-5">

                </div>
            </div>
            <div class="content" style="text-align: justify;">
                @yield('content')
            </div>
        </div>
    </div>
</body>
</html>
