@if (isset($type) && $type == 'excel')
    @include('exports.component.header')

    <table>
        <thead>
        <tr>
            <th>Report Date</th>
            <th>{{$data['range']}}</th>
        </tr>
        <tr>
            <th>Date Issued</th>
            <th>{{$data['created_by']}}</th>
        </tr>
        <tr>
            <th>Generated By</th>
            <th>{{$data['created_at']}}</th>
        </tr>
        </thead>
    </table>

    <br>
    <br>
@endif
@yield('content')
